### ISSUE TITLE
Please change bugtracker link

### ISSUE THREAD

**Issue by pcav** [Mi-Kbs-gis/TlugProcessing#1]
It currently points to the repo, not to the issues page.
Thanks.

**Comment by Mi-Kbs-gis** [comment]
Is solved, Will be published with the next release.

**Comment by pcav** [comment]
Please do not close the ticket until it is actually solved in the current release.
in code it is still `tracker=https://github.com/Mi-Kbs-gis/TlugProcessing`
Thanks.
